### ISSUE TITLE
Argument and Config Parser

### ISSUE THREAD

**Issue by morgenmuesli** [SE-Projekt-LED-Detection/LED-Detection#75]
## Description
We need an argument and config parser with that the user can either enter a config file or type in the Configuration with the command line interface.
The Config file could be in yaml syntax.

## Example config

```yaml
version: 0.1 # Version number of the config file to ensure backward compatibility

#required
reference_path: sample.json

# optional, default is None
broker_path: "mqtt://sample.com"
broker_port: 8883

# optional, default is 0
cam_port: 1
logging_level: "default" # serenity level"
log_file: out.log # path for logging
activate_visualizer: True #default is False
validity_seconds: 300 #default is 300, time for the homography matrix to be recalculated
 

```
